name: "[activity-worker] CI - Lint"

on:
  pull_request:
    paths:
      - "activity-worker/**"
      - ".github/workflows/ci-activity-worker.yaml"
  push:
    paths:
      - "activity-worker/**"
      - ".github/workflows/ci-activity-worker.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Install tools
        run: mise --cd activity-worker install
      - name: Lint
        run: mise --cd activity-worker run lint
