name: "[worker] CI - Lint"

on:
  pull_request:
    paths:
      - "worker/**"
      - ".github/workflows/ci-worker.yaml"
  push:
    paths:
      - "worker/**"
      - ".github/workflows/ci-worker.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Install tools
        run: mise --cd worker install
      - name: Lint
        run: mise --cd worker run lint
      - name: Check formatting
        run: mise --cd worker run format
